sudo: required
language: java
jdk:
  - openjdk11
services:
  - docker
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - secure: "vzzW4BjfAjgP7TLnOy5C2dBzfPCVnoVh3SIZEo0cNPvM6ng82szP7n7A0P2dqkjLqDCWyQCdAJ3wvtamX+WJWAGPCEMafbZtCB58eUeDXoJCIDnHfsslh1/40SImWPKe6RQWz9vO8DCVm5lVZqDsw4Mnv8QGW/sF5jlwR6QleHejQcIR+TKV+qufC9ykRKffepnPN/YlFQQNU9aXVR0ox0Yp/4onLjiuO5lVXRcZT/Qkxk+ufIZvXAGp2FsVwVugiVARX4eX3KpSkvFO2qVo6qNZwpxDKfgahZfEIFrmWKS02OSkmMDHV/UZ3qylZ6c5KKYRW0OmR+AR3wOcUt029y+ZT8PspzwkmEm3hTp7JZcjZmMVE4mc7XisH/ZxOS7QBJV/dYtk+UB0KbBl3LbSQ98c/qWc8jqQJaV7wbwc/vrPAbs7DgndZnyZZlKQMeiuXWQZ0Y8sEUwP6o4/S0WR7Vra9zC5uJRjJH5JPPnJug+dSPo3+23b8X4cN0rRLPmalmHkqC4Lau8ZoRvRo1k4ZgCQXZizVOZKO59WNKwXG860jm4XrHoxQeOYE0ryh/fINngMdNQmFE4yWaVJbtKNa7UEQD5hOIkusNA80b8Dg3WAkigcYUK0TgyQ84kMx1rqNzIKmn1NcH0BRvgiaYXBYwba9Z9fuBFS54z0cAWgkaE="
    - secure: "DPal7qNr4f8Y6ECIPQwO/N4uhOKX2PFXXHsgXHvaClIwlmwyyg2RiDmuAQwL/mQ3YqbtHP+y7fp/a0uVhUyybLwLp751cXPbfCq77C47nbXkp+DNOOVvP5tKU2ysbQc9Pe+32dNNcWljKML/NBnmP+++Qe5svLrEtvLMMGNmM8Nxggs4m4RSGDHd+GWprGjrVqkHc/HA5pjjw8lONT0ahTTDDKfVngLkO3gr3xeiL369PwqZuIY4BoC4De/jY15OmNDNGhAVPkiLUavnNOHw2D/RpZqEAGVt9pw5fdkcPVPRsoe1kcQtMvy/xVxAbJIxTH3hxQhX5G0LfxZYhNuZyYVDoZN266moYql1+TnU3oHwhj/VsA2LbBKTks6vQXTpocfRZhzSOjgnu/mHYLdDgTC1DaXdPMhtAszGicV1dcb3XsbSvqh8H9SaJb3tpf6VYjTdfWfSQYXRD4QKiJlxS45Geso1H9f3W4fArPMGj8u1u9OQzON0lMx5OVoLvkW1bz75FPgAjH8O8i78SzTXXfd9LMdov1vMK5M0mqb7A7ACoST3ozw8/6uXQExea2RIrVpoCdpY/n7j+Vrh3gSETmIbvsk5HZR7y6pCL4206boBpKVu0JqKn9v0T2tJmWMjhGiiwunGxDnlVQtSfm2sjNcpGdJQqY4Dhbl93hNYkZg="
    # AWS_ACCESS_KEY_ID
    - secure: "KVzaDWEBVPJkyw3ISXWBYtPpu5z8g6Ksna6nL32EfYlXEvbd/eCRDktFUhKCAyg4ZiDEBn3U7vvVyIeyIK5paDDVUytSby7yQ3k4AvN//w8/UMld0RXQSPNGLc2knqK44EINxzLP2C5k9Qh8JsWBWLazWlBN0Fj7SlF8bylBvZnbwVa4vhqONChap8lHivRzfS0kZho6G7FsqcKrbRwZLKktsdH3Mbs/LQZSNizhhHF5SHaihWherkPKnDio1FlD1QSlMDEjdd0UqkEOi+4jc1ASXr4q7XqgfBKoNdjxHTxfzvlrya84hm1hQfZ1WKLjkltO5mmmhvoPs04yLhx5yCTy8uCxtZftvBo0s2YsVHSJo1v3O8QnglEj//BdyhaMBWoiHMktxRBtSnPVxtXLSGkpQ0J+4VuS40sWyEm779rFALv0b3JBKuTkcwp2tKcu64t+YAv0g0S1wlkvJ+wHxsPratgM2NuhNmj/TJBi8eAed6juLYb/0aDImfZ95Jo54syMNFNw5ZlnlNQbNeDHAslKJ4klHVcqCIi/B6gPpH/G5he5MUn24OoICdR4UEa73IzPmxLF2wCwsJjR3LI7R+ymGbMuVQwWf9kGad7OxXfw1DOl9Eld/mDoqqZ2VKMjyV4tjUjsMKavojqNU03tKhMFBRVq01U58gJAAYq9dt8="
    # AWS_SECRET_ACCESS_KEY
    - secure: "QQYjZnZfPHAH/0wXNl5RhgNrcqcLPhT8Ycfk/NYOv4amFLYjyMSLBE6+BtQZcSr1LzcZvjJMFqb3pfv1xdXMTqTV6rl916m8vbz5ZnvvgzIo5R5d+gF2UJitQBOzLQZNXGKXYhxaAD/LVAWrW11FKUs9hw0LgGlH1U7wI3RYt9D7DH0Y50u2mhqoirzEmI0pXkxBy4Ema64rSyXW/1clIPfobGs4IDBwfE7GHTteUZ56JDjlukOATDyIEDnk5OkSvFP44NfGpGabMiAuE3xxuC/rBHoze+yyeOi6+frm9TtvAQwqxruidGKIuySa8irf4L4kPDnSMFTZUP9AvbcC5kqCS12mSCaPm3la41hU7nZWuiSGvs2jApH9ABC0g8K0UjRLG3DgU2DEScoElpGCZz8EcSNFV35onxtF8h7hZvoe0vMJCeDrR7XPQtcuShOfZ/xi8nhmS8eaTCWO4Sh4i5dDABqbiZhPzRyaFZwydkVs9xcALYi8VaJcpjErBuIjc0ybMJVOdHrEhBlOTIYVypbGvwilgXHqHwErlql1Nj3vK5S/KLImKDzpoYTchMaxnN/mdF/Ju9oTzVEgXZF71PV/qg91Pyc/j6r/ugs/e/ARlfIMEimWuhsw4sYagK88euLxT7HztH+bNfp8CJdnHFDKMoQPlBLDFt3+VIHo6gM="

install:
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
  - export ARTIFACT_NAME="vtj-service"

script:
  - mvn clean install -B -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}

  - mv vtj-service/target/vtj-service.war $DOCKER_BUILD_DIR/artifact/
  - mv vtj-test-ws/target/vtj-test-ws.jar $DOCKER_BUILD_DIR/artifact/
  - cp -vr src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/

  - export BASE_IMAGE="baseimage-war-openjdk11:master"
  - ./ci-tools/common/pull-image.sh
  - ./ci-tools/build/build-war.sh $ARTIFACT_NAME

  - export BASE_IMAGE="baseimage-fatjar-openjdk11:master"
  - ./ci-tools/common/pull-image.sh
  - ./ci-tools/build/build-fatjar.sh vtj-test-ws

deploy:
  - provider: script
    script: mvn deploy -pl vtj-api -am -DskipTests --settings ci-tools/common/maven-settings.xml
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: ./ci-tools/build/upload-image.sh $ARTIFACT_NAME && ./ci-tools/build/upload-image.sh vtj-test-ws
    on:
      all_branches: true
