sudo: required
language: java
jdk:
  - openjdk11
services:
  - docker
cache:
  directories:
    - $HOME/.m2
env:
  global:
    # ARTIFACTORY_USERNAME
    - secure: "uyFslKEtBSnL4EkzY71PXsvCGlZYdTuF+9igQOzfa04RmE2Z0OJFfaBPsj8afhFkf6oGQTwyhsPohxh7/81OOWlryzZh7HolfTiNuKYBx6xg0T+0lCIUf89/H2fpN6vE5fh6rZdfAA4ZeLNNAdov+uIkB8NbaMXuwgHNJGKeUCKqP/PXbg8k3fpqDfvH0v8zSG+OumefcBUyu7kCWEHCK5jItFZ/bEqMlGF26B9otJCVyIBAvOSqBnh7wI3DjWrRTavsmsZ68nVAXWbT5H+S2GxCuyP0HxNYQ3CKAgkk6cyy+jglrl6Zh4/AorRLb3csHo/6UZODwKEGzB4rOZIPxoNFR5KM5ZXFZe7nwWJQP2mdlwK0358NjKECdHFzqyRJcTPB8TI5tiqH3HEL1BDRvE7ESgLSSGlvDwJN8UUaaXkgFUoL66+Pg/4cfqOlaxLzxdVCkcqec71JdkICm7b5CJjpWqIGMYMRiyGSu3Zmk1H+H9qr5tCB0vvsnEE65EJS62t+tZ1ACZjYAQcZlt3zW8GcClXp/ZTKH8H+TRIdzvn5aihGxY7JDCukYJjlXV3t/gMWDrzHYQxEXKFxQvQlT7LIL3T90glEzdUgFn4CXgP7rQ8fhz/m2JJa9IX9QS64plncAz53jysUd8xnyUs99Tb1z6Ci1Yjq+MlVpyvJoy8="
    # ARTIFACTORY_PASSWORD
    - secure: "EgDQgjhi50EyguvkMJnlkLnJSLYE4oJYHWL1FMQ+JGV0U/NpPf0pkjVW2IqOaor4fbZv7aOE4F2SZ9tnRWqnj8eXh1kEiGDIiYMKjsLZe+sOgyWYx69D3+tMZKu8aY+L/EvfjwRhDZuqCiXXEOs3gd7j97Pm0yTYQq/PSkx5cAg4SwfdHlx3m9qqQbtrcFewFIquLf5eNxQr7VUQagp8rvOJ1RfjP0ev6DOuE1OKEseeQQ6Aoqc+my8ARAykxCS7Zyrh2tsbL2pxQjZiBcCYLvFxssWY2p5dMXma8ZMvNw/YdVtmOS+agrvtwCqVLLzXVd2Kh1JPV5Spwa0NE7WjBo5655UMYNt1o2uPdVlI0vUbTnsu0F911LQP6b1I5n7SzpKCykXOsIvo1S/HTSJUU/B69JiBJM4TN1Fd3qtI4TAHM+zSk36GYgbgV3DH7HXq2A/PrukP1OcGGSupubiSDCJAm4pN4ELreMYS7n6T7e0LFXPKhdClc48zzzaeWPJlxhrmcJxCh6GLkOfduO+rX5GXp0mQwSxstRElmt57atDq7y1vn0ObHKOGSE/Kx2X7Xl+QAoOHiZTHXabEAtI9MLd2YhAznek04PGeWC0hRIh8PZ5dQaoF09c0bY9WF1zc+SSUBz2z+Gy+/0fK8bT0O2hO3Db9mwu3zf21vuDiuQg="
    # AWS_ACCESS_KEY_ID
    - secure: "KVzaDWEBVPJkyw3ISXWBYtPpu5z8g6Ksna6nL32EfYlXEvbd/eCRDktFUhKCAyg4ZiDEBn3U7vvVyIeyIK5paDDVUytSby7yQ3k4AvN//w8/UMld0RXQSPNGLc2knqK44EINxzLP2C5k9Qh8JsWBWLazWlBN0Fj7SlF8bylBvZnbwVa4vhqONChap8lHivRzfS0kZho6G7FsqcKrbRwZLKktsdH3Mbs/LQZSNizhhHF5SHaihWherkPKnDio1FlD1QSlMDEjdd0UqkEOi+4jc1ASXr4q7XqgfBKoNdjxHTxfzvlrya84hm1hQfZ1WKLjkltO5mmmhvoPs04yLhx5yCTy8uCxtZftvBo0s2YsVHSJo1v3O8QnglEj//BdyhaMBWoiHMktxRBtSnPVxtXLSGkpQ0J+4VuS40sWyEm779rFALv0b3JBKuTkcwp2tKcu64t+YAv0g0S1wlkvJ+wHxsPratgM2NuhNmj/TJBi8eAed6juLYb/0aDImfZ95Jo54syMNFNw5ZlnlNQbNeDHAslKJ4klHVcqCIi/B6gPpH/G5he5MUn24OoICdR4UEa73IzPmxLF2wCwsJjR3LI7R+ymGbMuVQwWf9kGad7OxXfw1DOl9Eld/mDoqqZ2VKMjyV4tjUjsMKavojqNU03tKhMFBRVq01U58gJAAYq9dt8="
    # AWS_SECRET_ACCESS_KEY
    - secure: "QQYjZnZfPHAH/0wXNl5RhgNrcqcLPhT8Ycfk/NYOv4amFLYjyMSLBE6+BtQZcSr1LzcZvjJMFqb3pfv1xdXMTqTV6rl916m8vbz5ZnvvgzIo5R5d+gF2UJitQBOzLQZNXGKXYhxaAD/LVAWrW11FKUs9hw0LgGlH1U7wI3RYt9D7DH0Y50u2mhqoirzEmI0pXkxBy4Ema64rSyXW/1clIPfobGs4IDBwfE7GHTteUZ56JDjlukOATDyIEDnk5OkSvFP44NfGpGabMiAuE3xxuC/rBHoze+yyeOi6+frm9TtvAQwqxruidGKIuySa8irf4L4kPDnSMFTZUP9AvbcC5kqCS12mSCaPm3la41hU7nZWuiSGvs2jApH9ABC0g8K0UjRLG3DgU2DEScoElpGCZz8EcSNFV35onxtF8h7hZvoe0vMJCeDrR7XPQtcuShOfZ/xi8nhmS8eaTCWO4Sh4i5dDABqbiZhPzRyaFZwydkVs9xcALYi8VaJcpjErBuIjc0ybMJVOdHrEhBlOTIYVypbGvwilgXHqHwErlql1Nj3vK5S/KLImKDzpoYTchMaxnN/mdF/Ju9oTzVEgXZF71PV/qg91Pyc/j6r/ugs/e/ARlfIMEimWuhsw4sYagK88euLxT7HztH+bNfp8CJdnHFDKMoQPlBLDFt3+VIHo6gM="

install:
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
  - export ARTIFACT_NAME="vtj-service"

script:
  - mvn clean install -B -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}

  - mv vtj-service/target/vtj-service.war $DOCKER_BUILD_DIR/artifact/
  - mv vtj-test-ws/target/vtj-test-ws.jar $DOCKER_BUILD_DIR/artifact/
  - cp -vr src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/

  - export BASE_IMAGE="baseimage-war-openjdk11:master"
  - ./ci-tools/common/pull-image.sh
  - ./ci-tools/build/build-war.sh $ARTIFACT_NAME

  - export BASE_IMAGE="baseimage-fatjar-openjdk11:master"
  - ./ci-tools/common/pull-image.sh
  - ./ci-tools/build/build-fatjar.sh vtj-test-ws

deploy:
  - provider: script
    script: mvn deploy -pl vtj-api -am -DskipTests --settings ci-tools/common/maven-settings.xml
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: ./ci-tools/build/upload-image.sh $ARTIFACT_NAME && ./ci-tools/build/upload-image.sh vtj-test-ws
    on:
      all_branches: true
