sudo: required
language: java
jdk:
  - openjdk11
services:
  - docker
cache:
  directories:
    - $HOME/.m2
env:
  global:
    # ARTIFACTORY_USERNAME
    - secure: "kIft/yxoICczhVlXBa+48fwizap1noQj7NtJoHJ0gtXTMNT4Jq2zuW1p1uH7usbAbibmVyVhhCu6A1Ok983NYsD0ZrDLgjGpLMqMyE0GRHfy1JO8qEtpuGKbzhsqcbmyMCDcKaKVawWD/vg8P4AvuS+JtZDc39iv97eHDj+fS7Qe6JBo6lSDrsdyGlDOAFTixnDmmveT8wyM9PoToJ749OZ3nqe1qICva+aee+0OfUU1hGOWCaYhoVhuBRkrngQJYtU1dlDAFLdLYuKa4QDNUHATpT17TuTHn70vKQoeKPyCg0182Lrjym1bqDbtZJrxlsQB1rgTZrIes7JJN72tFwZBxa54yBHb+Lec37FJ1WYwWwqnPTkPP6xc9hSmo8LUf8RmR8Nv/HJHSJAD13w0sgsJTCE0E/X530Ga5LFfm5UCPOgutSZd+jnYyPjs6l/TO1LWDFrSy21D/qQjLR9F1THroV41UsRCqyUCykvtGbwbLxKD9EYvHqeyJhpN84TyB85S+b805UyZgO+IGvIi2+hXamZZbNVZxuWT4r0Iz5CJuEQvDP5lZfQ1hBWvSRy1EvXKJqIxnzJE1FYkstQAMZeG+jm3nH2AQE1brjpMbVP0U64g0CcT3+N7sOGusD3/wKn3pbTv+zUcwTHA8dHl6VXPgn64l/IfWzQWJyUFW9U="
    # ARTIFACTORY_PASSWORD
    - secure: "UTGEH+b2BHpHf5uwaZ4lyOXR4y1Pd1JqxLvSQDxQTs9laTk7Zkt88MHZ+3c4EheBj3kr97O1bO+PY6MxDaKsvUkcdAnqRo/xQwICNcvkgOzQgP9tkbZkoADvgbbXqbl/cvEVQH7a6F6I7UVTjoC+ieXwsyKmhkYZoqB8/HJvD3j5/nOMVw6g40gVVoPss8c2hWDs4k8R/e8VuNjWlHbR90SA0acf9rF5Ci4vvHJT27rqppOaH31cbCgFhXvaaJKwZ7sKjCL7mbMBFeMENXnuw8aQrlD6Zm06JLdqbRLIVkRIclHiv7weNET9+sVinCD5xyaUvh+jm7FVgxbw8mVWGNvxaysuQDHStspvCV3wQTb2pZKqM4OmxLWxpNy3cS04Q92BMO1M29TcyaPKwjuipV85IYaq1ho0EkG0Pm1CrpW6cpVeElpBJGAWCRKvxDwojWALQia71OzD2KY3ztdrPyfo2KW9lnjmf+fDCVLdgeWsw8so+tdfQK8q9Xt4ynyOf5Bfl2gWyF/d1eXkp+f6dAWvEVlx4FGHjJYeXHoUjdmYUZ0+SnToGryWgDr3UfFldSRKIMOTrzbgmzzlw+BCsR7J4LG+shtnkthnnlvp//fqZmTaX1uoImrPZFFglY5qjySbfT8jCSXGzVMxJYRmLUAqiPcNTOPeaIAb0jWazVQ="
    # AWS_ACCESS_KEY_ID
    - secure: "KVzaDWEBVPJkyw3ISXWBYtPpu5z8g6Ksna6nL32EfYlXEvbd/eCRDktFUhKCAyg4ZiDEBn3U7vvVyIeyIK5paDDVUytSby7yQ3k4AvN//w8/UMld0RXQSPNGLc2knqK44EINxzLP2C5k9Qh8JsWBWLazWlBN0Fj7SlF8bylBvZnbwVa4vhqONChap8lHivRzfS0kZho6G7FsqcKrbRwZLKktsdH3Mbs/LQZSNizhhHF5SHaihWherkPKnDio1FlD1QSlMDEjdd0UqkEOi+4jc1ASXr4q7XqgfBKoNdjxHTxfzvlrya84hm1hQfZ1WKLjkltO5mmmhvoPs04yLhx5yCTy8uCxtZftvBo0s2YsVHSJo1v3O8QnglEj//BdyhaMBWoiHMktxRBtSnPVxtXLSGkpQ0J+4VuS40sWyEm779rFALv0b3JBKuTkcwp2tKcu64t+YAv0g0S1wlkvJ+wHxsPratgM2NuhNmj/TJBi8eAed6juLYb/0aDImfZ95Jo54syMNFNw5ZlnlNQbNeDHAslKJ4klHVcqCIi/B6gPpH/G5he5MUn24OoICdR4UEa73IzPmxLF2wCwsJjR3LI7R+ymGbMuVQwWf9kGad7OxXfw1DOl9Eld/mDoqqZ2VKMjyV4tjUjsMKavojqNU03tKhMFBRVq01U58gJAAYq9dt8="
    # AWS_SECRET_ACCESS_KEY
    - secure: "QQYjZnZfPHAH/0wXNl5RhgNrcqcLPhT8Ycfk/NYOv4amFLYjyMSLBE6+BtQZcSr1LzcZvjJMFqb3pfv1xdXMTqTV6rl916m8vbz5ZnvvgzIo5R5d+gF2UJitQBOzLQZNXGKXYhxaAD/LVAWrW11FKUs9hw0LgGlH1U7wI3RYt9D7DH0Y50u2mhqoirzEmI0pXkxBy4Ema64rSyXW/1clIPfobGs4IDBwfE7GHTteUZ56JDjlukOATDyIEDnk5OkSvFP44NfGpGabMiAuE3xxuC/rBHoze+yyeOi6+frm9TtvAQwqxruidGKIuySa8irf4L4kPDnSMFTZUP9AvbcC5kqCS12mSCaPm3la41hU7nZWuiSGvs2jApH9ABC0g8K0UjRLG3DgU2DEScoElpGCZz8EcSNFV35onxtF8h7hZvoe0vMJCeDrR7XPQtcuShOfZ/xi8nhmS8eaTCWO4Sh4i5dDABqbiZhPzRyaFZwydkVs9xcALYi8VaJcpjErBuIjc0ybMJVOdHrEhBlOTIYVypbGvwilgXHqHwErlql1Nj3vK5S/KLImKDzpoYTchMaxnN/mdF/Ju9oTzVEgXZF71PV/qg91Pyc/j6r/ugs/e/ARlfIMEimWuhsw4sYagK88euLxT7HztH+bNfp8CJdnHFDKMoQPlBLDFt3+VIHo6gM="

install:
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
  - export ARTIFACT_NAME="vtj-service"

script:
  - mvn clean install -B -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}

  - mv vtj-service/target/vtj-service.war $DOCKER_BUILD_DIR/artifact/
  - mv vtj-test-ws/target/vtj-test-ws.jar $DOCKER_BUILD_DIR/artifact/
  - cp -vr src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/

  - export BASE_IMAGE="baseimage-war-openjdk11:master"
  - ./ci-tools/common/pull-image.sh
  - ./ci-tools/build/build-war.sh $ARTIFACT_NAME

  - export BASE_IMAGE="baseimage-fatjar-openjdk11:master"
  - ./ci-tools/common/pull-image.sh
  - ./ci-tools/build/build-fatjar.sh vtj-test-ws

deploy:
  - provider: script
    script: mvn deploy -pl vtj-api -am -DskipTests --settings ci-tools/common/maven-settings.xml
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: ./ci-tools/build/upload-image.sh $ARTIFACT_NAME && ./ci-tools/build/upload-image.sh vtj-test-ws
    on:
      all_branches: true
