version: "3.3"
services:
  vtj-service:
    build: ./vtj-service
    ports:
      - "8080:8080"
    volumes:
      - ./dev_keys:/root/oph-environment/authentication/vtj-service:ro
  vtj-test-ws:
    build: ./vtj-test-ws
    environment:
      - vtj.testws.ssl-enabled=true
      - vtj.testws.client-auth=want
      - vtj.testws.oppijanumerorekisteri.enabled
      - vtj.testws.oppijanumerorekisteri.address
      - vtj.testws.oppijanumerorekisteri.username
      - vtj.testws.oppijanumerorekisteri.password
      - web.url.cas
#      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,address=*:8001,server=y,suspend=n"
#    ports:
#      - "8001:8001"
    volumes:
      - ./dev_keys:/root/oph-environment/authentication/vtj-service:ro
