version: "3.3"
services:
  vtj-service:
    build: ./vtj-service
    ports:
      - "8080:8080"
    volumes:
      - ./dev_keys:/root/oph-environment/authentication/vtj-service:ro
  vtj-test-ws:
    build: ./vtj-test-ws
    environment:
      - vtj_testws_ssl_enabled=true
      - vtj_testws_client_auth=want
      - vtj_oppijanumerorekisteri_enabled
      - vtj_oppijanumerorekisteri_host
      - vtj_oppijanumerorekisteri_username
      - vtj_oppijanumerorekisteri_password
#      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,address=*:8001,server=y,suspend=n"
#    ports:
#      - "8001:8001"
    volumes:
      - ./dev_keys:/root/oph-environment/authentication/vtj-service:ro
