version: "3.3"
services:
  vtj-service:
    build: ./vtj-service
    ports:
      - "8080:8080"
    volumes:
      - ./dev_keys:/root/oph-configuration/keys:ro
  vtj-test-ws:
    build: ./vtj-test-ws
    volumes:
      - ./dev_keys:/home/vtj/keys:ro
