-- testihenkilöt vanhasta vtj-servicen mockista

-- jag tar ingen ansvar för dålig svenska... :/
INSERT INTO kotimainen_osoite (katu_fi, katu_sv, katunumero, porraskirjain, huoneistonumero, jakokirjain, postinumero, postitoimipaikka_fi, postitoimipaikka_sv) VALUES
  ('Mannerheimintie', 'Mannerheiminväg', 45, 'A', 12, null, '00101', 'Helsinki', 'Helsingfors'),
  ('Mannerheimintie', 'Mannerheiminväg', 45, 'A', 22, null, '00100', 'Helsinki', 'Helsingfors'),
  ('Mannerheimintie', 'Mannerheiminväg', 45, 'A', 22, null, '00101', 'Helsinki', 'Helsingfors'),
  ('Mannerheimintie', 'Mannerheiminväg', 45, 'A', 33, null, '00100', 'Helsinki', 'Helsingforss'),
  ('Mannerheimintie', 'Mannerheiminväg', 45, 'A', 44, null, '00100', 'Helsinki', null),
  ('Keskikatu', 'Central gatan', 100, null, null, null, '98765', 'Pohjanmaa', 'Österbotnia'),
  ('Uusikatu', 'Nya gatan', 100, null, null, null, '12345', 'Auramaa', 'Åraland'),
  ('Vanhakatu', 'Gamla gatan', 100, null, null, null, '54321', 'Kymimaa', 'Kymilandet'),
  ('Vanhakatu', 'Gamla gatan', 200, null, null, null, '56321', 'Hämemaa', 'Hämelandet');

INSERT INTO henkilo (henkilotunnus, etunimet, kutsumanimi, sukunimi, sukupuoli, sahkoposti, kansalaisuus, kotimainen_osoite_id) VALUES
  ('010156-9994', 'Tobias Nikolas',              null,       'Siltanen',          'MIES', null, '246', null),
  ('010547-9991', 'Milo Ingvald Rami',           null,       'Reponen',           'MIES', null, '246', null),
  ('010661-999E', 'Veeti Valtteri',              null,       'Seppä',             'MIES', null, '246', null),
  ('010673-998H', 'Meiju Sanna-Maria Taika',     null,       'Junnila',           'NAINEN', null, '246', null),
  ('010745-9983', 'Claudia Heidi',               null,       'Gustafsson',        'NAINEN', null, '246', (SELECT id FROM kotimainen_osoite WHERE katu_fi = 'Mannerheimintie' AND katunumero = 45 AND porraskirjain = 'A' AND huoneistonumero = 12)),
  ('010849-999Y', 'Joel Niila',                  null,       'Ahonen',            'MIES', null, '246', (SELECT id FROM kotimainen_osoite WHERE katu_fi = 'Mannerheimintie' AND katunumero = 45 AND porraskirjain = 'A' AND huoneistonumero = 22 AND postinumero = '00100')),
  ('010873-9973', 'Felix Jonathan',              null,       'Haapakoski',        'MIES', null, '246', null),
  ('010957-998T', 'Vickan',                      null,       'Tuulispää',         'NAINEN', null, '246', null),
  ('010973-999Y', 'Kaija',                       null,       'Tuulispää',         'MIES', null, '246', (SELECT id FROM kotimainen_osoite WHERE katu_fi = 'Mannerheimintie' AND katunumero = 45 AND porraskirjain = 'A' AND huoneistonumero = 22 AND postinumero = '00101')),
  ('010973-999X', 'Joni Kaj',                    null,       'Hiltunen',          'MIES', null, '246', null),
  ('011066-998X', 'Maija Evi',                   null,       'Puumalainen',       'NAINEN', null, '246', null),
  ('011073-998R', 'Silja',                       null,       'Loikkanen',         'NAINEN', null, '246', null),
  ('020637-998V', 'Jane Kukka-Maaria',           null,       'Putkonen',          'NAINEN', null, '246', null),
  ('030668-998H', 'Aliisa Lumia',                'Lumia',    'Pietikäinen',       'NAINEN', null, '246', null),
  ('031042-9981', 'Isabelle Riia',               null,       'Kivimäki',          'NAINEN', null, '246', null),
  ('031173-999V', 'Ismo',                        null,       'Neuvonen',          'MIES', null, '246', null),
  ('031251-9990', 'Mohamed Mohamed Mustafa',     null,       'Lindroos',          'NAINEN', null, '246', null),
  ('040779-998T', 'Pihla Kukka-Maria',           null,       'Haapakoski',        'NAINEN', null, '246', null),
  ('040946-999X', 'Simeon Samuli',               null,       'Aarnio',            'MIES', null, '246', null),
  ('050654-9997', 'Helge Abel',                  null,       'Kiviniemi',         'MIES', null, '246', null),
  ('080104A9997', 'Eric Folke',                  null,       'Männikkö',          'MIES', null, '246', null),
  ('130139-998E', 'Ulla Rea',                    null,       'Pekkala',           'NAINEN', null, '246', null),
  ('140977-998B', 'Svetlana Päivi',              'Päivi',    'Männikkö',          'NAINEN', null, '246', null),
  ('170479-999T', 'Hans',                        null,       'Ollila',            'MIES', null, '246', null),
  ('201100A9990', 'Elias Kristian',              null,       'Männikkö',          'NAINEN', null, '246', null),
  ('251102A996M', 'Eriika Mailis',               null,       'Männikkö',          'NAINEN', null, '246', null),
  ('260991-999R', 'Ilmari Folke',                null,       'Huhtiistinen',      'MIES', null, '246', null),
  ('261148-9987', 'Sanelma Alice',               null,       'Ruuska Malila',     'NAINEN', null, '246', null),
  ('270569-998E', 'Kielo Janica',                null,       'Pietikäinen',       'NAINEN', null, '246', null),
  ('040188-999A', 'Ali Julian Fjalar',           null,       'Marttila',          'MIES', null, '246', null),
  ('050351-9980', 'Maarita Alicia',              null,       'Holmberg',          'NAINEN', null, '246', null),
  ('061191-998D', 'Aliisa Maiju Rebecca',        null,       'Kujala',            'NAINEN', null, '246', null),
  ('070356-999L', 'Mikke Samuli',                null,       'Laaksonen',         'MIES', null, '246', (SELECT id FROM kotimainen_osoite WHERE katu_fi = 'Mannerheimintie' AND katunumero = 45 AND porraskirjain = 'A' AND huoneistonumero = 33)),
  ('160279-999J', 'Matti Eemeli',                'Eemeli',   'Meikäläinen',       'MIES', null, '246', (SELECT id FROM kotimainen_osoite WHERE katu_fi = 'Mannerheimintie' AND katunumero = 45 AND porraskirjain = 'A' AND huoneistonumero = 44)),
  ('160498-9992', 'Vili Jimmy',                  null,       'Saukkonen',         'MIES', null, '246', null),
  ('171047-999C', 'Allan Kent',                  null,       'Minkkinen',         'MIES', null, '246', null),
  ('191148-999R', 'Dmitri Jonathan',             'Jonathan',  'Kataja',           'MIES', null, '246', null),
  ('200470-998C', 'Nella Pihla-Roosa',           null,       'Junnila',           'NAINEN', null, '246', null),
  ('201171-999A', 'Elmo',                        null,       'Andersson',         'MIES', null, '246', null),
  ('220576-9992', 'Ali Allan',                   null,       'Holopainen',        'MIES', null, '246', null),
  ('230197-999W', 'Gabriel Jalo Päiviö',         null,       'Pekkala',           'MIES', null, '246', null),
  ('101019-998L', 'Beatrice Kukka-Maaria',       null,       'Hirvelä',           'NAINEN', null, '246', null),
  ('290154-999N', 'Erkki Taavetti Valtteri',     null,       'Hyvönen',           'MIES', null, '246', null),
  ('301275-998K', 'Sulevi Kukka-Maaria Maiju',   null,       'Männikkö',          'NAINEN', null, '246', null),
  ('250589-999B', 'Denis Usko',                  null,       'Järveläinen',       'NAINEN', null, '246', null),
  ('050369-999N', 'Jalmari Elof Pontus',         null,       'Setälä',            'MIES', null, '246', null),
  ('020894-9986', 'Agneta Kukka-Maaria',         null,       'Saukkonen',         'NAINEN', null, '246', null),
  ('291281-999H', 'Dennis Kaj',                  null,       'Koljonen',          'MIES', null, '246', null),
  ('150151-998U', 'Maj Evi',                     null,       'Lindell',           'NAINEN', null, '246', null),
  ('251199-999S', 'Eric Andrew',                 'Andrew',   'Pettersson',        'MIES', null, '246', null),
  ('250678-999A', 'Waldemar Olli-Pekka Andres ', 'Andres',   'Haanpää',           'MIES', null, '246', null),
  ('181003A999N', 'Ronny Bengt Thomas',          'Bengt',    'Setälä',            'MIES', null, '246', null),
  ('150478-9987', 'Minja Ella Nenna',            'Ella',     'Kolari',            'NAINEN', null, '246', null),
  ('081078-999K', 'Holger Raineri Kaino',        'Raineri',  'Soikkeli',          'MIES', null, '246', null),
  ('050815-998R', 'Lemmikki Alise',              'Alise',    'Ronkainen',         'NAINEN', null, '246', null),
  ('041248-999V', 'Bengt Valtteri',              'Valtteri', 'Koskela',           'MIES', null, '246', null),
  ('230896-9988', 'Sofi Ira Kukka-Maaria',       'Ira',      'Lyytinen',          'NAINEN', null, '246', null),
  ('270474-999Y', 'Robert Yrjö',                 'Yrjö',     'Hannula',           'MIES', null, '246', null),
  ('160582-998P', 'Lahja Nicole',                'Nicole',   'Kontkanen ',        'NAINEN', null, '246', null),
  ('110360-9986', 'Maija Aniitta',               'Aniitta',  'Hurskainen',        'NAINEN', null, '246', null),
  ('271062-999P', 'Pekka Joel',                  'Joel',     'Rautiainen ',       'MIES', null, '246', null),
  ('240984-999M', 'Rikhard Niila',               'Niila',    'Huusko',            'MIES', null, '246', null),
  ('130486-9980', 'Linda Neea',                  'Neea',     'Kuusinen',          'NAINEN', null, '246', null),
  ('090369-9998', 'Lenni Håkan',                 'Håkan',    'Kaukonen',          'NAINEN', null, '246', null),
  ('090271-998X', 'Meiju Maiju',                 'Maiju',    'Haapakoski',        'NAINEN', null, '246', null),
  ('010449-998P', 'Sonja Agneta/Aune Kukka',     null,       'von Braun de Karttunen', 'NAINEN', null, '246', null),
  ('010522-998J', 'Elina Kukka-Maaria',          null,       'Rossi',             'NAINEN', null, '246', null),
  ('150894-9877', 'Teppo',                       'Teppo',    'Testaaja',          'MIES', null, '246', null),
  ('150894-967K', 'Seppo',                       'Seppo',    'Testaaja',          'MIES', null, '246', null),
-- Vetuma
  ('010101-123N', 'Teemu',                       'Teemu',    'Testaaja',          'MIES', null, '246', null),
  ('210281-9988', 'NORDEA',                      'NORDEA',   'DEMO',              'NAINEN', null, '246', null),
  ('190306A9850', 'Pekka',                       'Pekka',    'Demo',              'MIES', null, '246', null),
  ('190308A948A', 'Liisa',                       'Liisa',    'Demo',              'NAINEN', null, '246', null),
  ('081181-9984', 'ANNA',                        'ANNA',     'TESTI',             'NAINEN', null, '246', null),
  ('010170-960F', 'Maija',                       'Maija',    'Meikäläinen',       'NAINEN', null, '246', null),
-- VTJ-update-tests static
  ('020260-909P', 'Matti',                       'Matti',    'Testinen',          'MIES', 'matti.meikalainen@fromvtj.oph', '246', (SELECT id FROM kotimainen_osoite WHERE katu_fi = 'Keskikatu' AND katunumero = 100)),
  ('020260-9833', 'Ville',                       null,       'Meikäläinen',       'MIES', 'ville.meikalainen@fromvtj.oph', '246', (SELECT id FROM kotimainen_osoite WHERE katu_fi = 'Uusikatu' AND katunumero = 100)),
  ('020260-941R', 'Teppo Seppo',                 'Teppo',    'Meikäläinen',       'MIES', 'seppo.meikalainen@fromvtj.oph', '246', (SELECT id FROM kotimainen_osoite WHERE katu_fi = 'Vanhakatu' AND katunumero = 100)),
  ('020260-961C', 'Matti Seppo',                 'Seppo',    'Matikainen',        'MIES', 'seppo.matikainen@fromvtj.oph', '246', (SELECT id FROM kotimainen_osoite WHERE katu_fi = 'Vanhakatu' AND katunumero = 200));

INSERT INTO henkilo_huoltaja (huoltaja_id, huollettava_id) VALUES
  ((SELECT id FROM henkilo WHERE henkilotunnus = '210281-9988'), (SELECT id FROM henkilo WHERE henkilotunnus = '190306A9850')),
  ((SELECT id FROM henkilo WHERE henkilotunnus = '210281-9988'), (SELECT id FROM henkilo WHERE henkilotunnus = '190308A948A'));
