server:
  ssl:
    enabled: ${vtj.testws.ssl-enabled:false}
    trust-store: "${vtj.truststore.file:/root/oph-environment/authentication/vtj-service/truststore.p12}"
    trust-store-password: "${vtj.truststore.password:password}"
    key-store: "${vtj.keystore.file:/root/oph-environment/authentication/vtj-service/keystore.p12}"
    key-store-password: "${vtj.keystore.password:password}"
    key-alias: "${vtj.testws.key-alias:vtj-test-ws}"
    key-password: "${vtj.testws.key-password:password}"
    client-auth: ${vtj.testws.client-auth:none}
    # TLSv1.3 ei tue optionaalista client-sertiä ("want")
    enabled-protocols: [TLSv1.2]
  servlet:
    context-path: "/vtj-test-ws"
  tomcat:
    accesslog:
            enabled: true
            directory: "${vtj.testws.accesslog-dir:${user.home}/logs}"
            prefix: "access_vtj-test-ws"
            suffix: ".log"
            pattern: "{\"timestamp\": \"%{yyyy-MM-dd'T'HH:mm:ss.SSSZ}t\", \"responseCode\": \"%s\", \"request\": \"%r\", \"responseTime\": \"%D\", \"requestMethod\": \"%m\", \"service\": \"vtj-test-ws\", \"environment\": \"${env.name}\", \"customer\": \"OPH\", \"user-agent\": \"%{User-Agent}i\", \"x-forwarded-for\": \"%{X-Forwarded-For}i\", \"x-real-ip\": \"%{X-Real-IP}i\", \"remote-ip\": \"%a\",  \"response-size\": \"%B\", \"referer\": \"%{Referer}i\"}"
            request-attributes-enabled: true
            rotate: true
            rename-on-rotate: true
            max-days: 7
    remote:
      port-header: X-Real-Port
    remoteip:
      protocol-header: X-Real-Proto
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
logging.level.root: "${env_loglevel:INFO}"
vtj-test-ws:
  oppijanumerorekisteri:
    enabled: ${vtj.testws.oppijanumerorekisteri.enabled:false}
    host: "${vtj.testws.oppijanumerorekisteri.host:'http://oppijanumerorekisteri'}"
    username: "${vtj.testws.oppijanumerorekisteri.username:${ssm_vtj_oppijanumerorekisteri_username:'not_used'}}"
    password: "${vtj.testws.oppijanumerorekisteri.password:${ssm_vtj_oppijanumerorekisteri_password:'not_used'}}"
  cas:
    host: "${host.cas:${vtj-test-ws.oppijanumerorekisteri.host}}"
