server:
  ssl:
    enabled: true
    trust-store: "${vtj-test-ws.trust-store:/root/oph-environment/authentication/vtj-service/truststore.p12}"
    trust-store-password: "${ssm_vtj_truststore_password:password}"
    key-store: "${vtj-test-ws.key-store:/root/oph-environment/authentication/vtj-service/keystore.p12}"
    key-store-password: "${ssm_vtj_keystore_password:password}"
    key-alias: "${vtj-test-ws.key-alias:vtj-test-ws}"
    key-password: "${ssm_vtj_keystore_password:password}"
    client-auth: want
    # TLSv1.3 ei tue optionaalista client-sertiä ("want" yllä)
    enabled-protocols: [TLSv1.2]
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
logging:
  file:
    name: "${vtj-test-ws.log-file:${user.home}/logs/oph-vtjtestws.log}"
logging.level.root: "${env_loglevel:INFO}"
logging.level.org.springframework.security: DEBUG
