name: vtj
on:
  workflow_dispatch:
  push:
    branches: [master]
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
          cache: "maven"
      - name: Maven version
        run: mvn --version
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn clean install -B -Dbranch=$GITHUB_REF_NAME -Drevision=$GITHUB_SHA -DbuildNumber=$GITHUB_RUN_NUMBER/$GITHUB_RUN_ATTEMPT
      - name: Upload vtj-service
        uses: actions/upload-artifact@v3
        with:
          name: vtj-service
          path: vtj-service/target/vtj-service.war
      - name: Upload vtj-test-ws
        uses: actions/upload-artifact@v3
        with:
          name: vtj-test-ws
          path: vtj-test-ws/target/vtj-test-ws.jar
  deploy-container:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Download vtj-service
        uses: actions/download-artifact@v3
        with:
          name: vtj-service
      - name: Download vtj-test-ws
        uses: actions/download-artifact@v3
        with:
          name: vtj-test-ws
      - name: Build Docker Container
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          git clone https://github.com/Opetushallitus/ci-tools.git
          source ci-tools/common/setup-tools.sh
          cp vtj-service.war $DOCKER_BUILD_DIR/artifact/
          cp vtj-test-ws.jar $DOCKER_BUILD_DIR/artifact/
          cp -vr src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/
          export ARTIFACT_NAME="vtj-service"
          export BASE_IMAGE="baseimage-war-openjdk11:master"          
          ./ci-tools/common/pull-image.sh
          ./ci-tools/github-build/build-war.sh $ARTIFACT_NAME
          ./ci-tools/github-build/upload-image.sh $ARTIFACT_NAME
          export ARTIFACT_NAME="vtj-test-ws"
          export BASE_IMAGE="baseimage-fatjar-openjdk11:master"
          ./ci-tools/common/pull-image.sh
          ./ci-tools/github-build/build-fatjar.sh $ARTIFACT_NAME
          ./ci-tools/github-build/upload-image.sh $ARTIFACT_NAME
  deploy-artifacts:
    needs: [build]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
          cache: "maven"
      - name: Maven version
        run: mvn --version
      - name: Deploy
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: |
          git clone https://github.com/Opetushallitus/ci-tools.git
          source ci-tools/common/setup-tools.sh
          mvn deploy -pl vtj-api -am -DskipTests --settings ci-tools/common/maven-settings.xml
